import type { BrandKit } from "../types";

// Brand kits. Os dois "Livre" replicam a linhagem visual dos carrosséis virais
// do MyPostFlow (referências em refs/): nascem destravados — liberdade total.
// Cores entram como tokens nos elementos; trocar de kit recolore tudo.
export const KITS: BrandKit[] = [
  {
    id: "livre-escuro",
    name: "Livre · Escuro",
    locked: false,
    bg: "#0A0A0B",
    surface: "#17171A",
    text: "#FFFFFF",
    muted: "#9A9AA2",
    accent: "#FFD60A",
    accent2: null,
    glow: null,
    fontDisplay: "Archivo Black",
    fontBody: "Inter",
    fontLabel: "Inter",
    logo: "@suamarca",
    motif: "minimal",
    eyebrow: "handle",
    note: "Preto + amarelo, headline condensada em caixa alta, realce ==assim==. Estilo viral dark.",
  },
  {
    id: "livre-claro",
    name: "Livre · Claro",
    locked: false,
    bg: "#FFFFFF",
    surface: "#F4F4F5",
    text: "#0E0E10",
    muted: "#62626B",
    accent: "#FF3B1F",
    accent2: null,
    glow: null,
    fontDisplay: "Inter",
    fontBody: "Inter",
    fontLabel: "Inter",
    logo: "@suamarca",
    motif: "minimal",
    eyebrow: "handle",
    note: "Branco editorial: headline preta com acento vermelho-laranja, ~cinza~ pra de-ênfase.",
  },
  {
    id: "editorial",
    name: "Editorial (referência)",
    locked: true,
    bg: "#100B0A",
    surface: "#1C1412",
    text: "#F7EFEA",
    muted: "#B5A8A2",
    accent: "#E8A39C",
    accent2: null,
    glow: "#EA580C",
    fontDisplay: "Fraunces",
    fontBody: "DM Sans",
    fontLabel: "Space Mono",
    logo: "@suamarca",
    motif: "glow",
    eyebrow: "pill-index",
    note: "Kit serifado com brilho quente.",
  },
  {
    id: "g2d-gestao",
    name: "G2D Gestão",
    locked: true,
    bg: "#0E0E10",
    surface: "#18181C",
    text: "#F4F1E8",
    muted: "#A8A496",
    accent: "#C9A84C",
    accent2: null,
    glow: "#C9A84C",
    fontDisplay: "Syne",
    fontBody: "DM Sans",
    fontLabel: "Space Mono",
    logo: "G2D",
    sub: "GESTÃO",
    motif: "glow",
    eyebrow: "pill-index",
  },
  {
    id: "g2d-licenciamentos",
    name: "G2D Licenciamentos",
    locked: true,
    bg: "#100D08",
    surface: "#1B160E",
    text: "#F4EFE4",
    muted: "#A99F8C",
    accent: "#C9A84C",
    accent2: null,
    glow: "#9a6b1f",
    fontDisplay: "Syne",
    fontBody: "DM Sans",
    fontLabel: "Space Mono",
    logo: "G2D",
    sub: "LICENCIAMENTOS",
    motif: "glow",
    eyebrow: "badge",
  },
  {
    id: "meraki",
    name: "Meraki",
    locked: true,
    bg: "#141019",
    surface: "#1E1726",
    text: "#F3F0F8",
    muted: "#A89DBA",
    accent: "#8B5CF6",
    accent2: null,
    glow: "#8B5CF6",
    fontDisplay: "Poppins",
    fontBody: "Poppins",
    fontLabel: "Space Mono",
    logo: "meraki",
    motif: "glow",
    eyebrow: "pill-index",
  },
];

export function getKit(id: string, customKits: BrandKit[] = []): BrandKit {
  return (
    customKits.find((k) => k.id === id) ??
    KITS.find((k) => k.id === id) ??
    KITS[0]
  );
}
